-- MySQL Script generated by MySQL Workbench
-- Mon Jul  5 01:44:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trip_calculator
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trip_calculator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trip_calculator` DEFAULT CHARACTER SET utf8 ;
USE `trip_calculator` ;

-- -----------------------------------------------------
-- Table `trip_calculator`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trip_calculator`.`category` (
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trip_calculator`.`item_set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trip_calculator`.`item_set` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `people` INT UNSIGNED NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trip_calculator`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trip_calculator`.`item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(20,2) UNSIGNED NULL,
  `note` TEXT(255) NULL,
  `category_name` VARCHAR(100) NOT NULL,
  `item_set_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_category_idx` (`category_name` ASC),
  INDEX `fk_item_item_set1_idx` (`item_set_id` ASC),
  CONSTRAINT `fk_item_category`
    FOREIGN KEY (`category_name`)
    REFERENCES `trip_calculator`.`category` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_item_set1`
    FOREIGN KEY (`item_set_id`)
    REFERENCES `trip_calculator`.`item_set` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trip_calculator`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trip_calculator`.`users` (
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trip_calculator`.`users_has_item_set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trip_calculator`.`users_has_item_set` (
  `users_name` VARCHAR(20) NOT NULL,
  `item_set_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`users_name`, `item_set_id`),
  INDEX `fk_users_has_item_set_item_set1_idx` (`item_set_id` ASC),
  INDEX `fk_users_has_item_set_users1_idx` (`users_name` ASC),
  CONSTRAINT `fk_users_has_item_set_users1`
    FOREIGN KEY (`users_name`)
    REFERENCES `trip_calculator`.`users` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_item_set_item_set1`
    FOREIGN KEY (`item_set_id`)
    REFERENCES `trip_calculator`.`item_set` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trip_calculator`.`item_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trip_calculator`.`item_has_users` (
  `item_id` INT UNSIGNED NOT NULL,
  `users_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`item_id`, `users_name`),
  INDEX `fk_item_has_users_users1_idx` (`users_name` ASC),
  INDEX `fk_item_has_users_item1_idx` (`item_id` ASC),
  CONSTRAINT `fk_item_has_users_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `trip_calculator`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_has_users_users1`
    FOREIGN KEY (`users_name`)
    REFERENCES `trip_calculator`.`users` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
